@echo off
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
start test_client
